apiVersion: v1
kind: Service
metadata:
  name: url-checker
  namespace: url-checker
  labels:
    app: url-checker
spec:
  type: LoadBalancer
  selector:
    app: url-checker   # stuurt verkeer naar pods met dit label
  ports:
    - name: http
      protocol: TCP
      port: 80         # poort waarop de Service luistert van buiten
      targetPort: 8080 # poort van de container
